[package]
name = "zkp-chaum-pedersen"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
num-bigint = { version = "0.4", features = ["rand"] }
hex = "0.4.3"

[build-dependencies]
tonic-build = "0.12.3"
